
server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: qwerty
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db.changelog/changelog-master.yml
    enabled: true
    drop-first: false
    mail:
      host: smtp.gmail.com
      port: 587
      username: bar.roszak@gmail.com
      password: Counterstrike11111
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true

