services:
  postgresDataBase:
    image: postgres:17.2
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: betterStudy
    #      POSTGRES_USERNAME: postgres
    restart: always
    ports:
      - "5433:5432"